version: '3.8'

name: "smart-repairs"

services: 

  #MySQL Service
  mariadb:
    image: "mariadb:${MARIADB_VERSION}"
    tty: true
    hostname: mariadb
    ports:
      - 3306:3306
    env_file: env/mariadb/db.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - db-network    
    healthcheck:
      test: 'mariadb -h localhost -u root -p${MYSQL_ROOT_PASSWORD}'
      interval: 5s
      timeout: 5s
      retries: 5   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    hostname: phpmyadmin
    ports:
      - 8080:80
    profiles: 
      - development
    networks:
      - db-network        
    depends_on:
      mariadb:
          condition: service_healthy      

#Docker Networks
networks:
  db-network:
    driver: bridge
  knowledge-network:
    driver: bridge  

#Volumes
volumes:
    dbdata:
      driver: local    