version: '3.8'

name: "smart-repairs"

include:
  - docker/database/compose.yml
  - docker/knowledge/compose.yml
  - docker/traefik/compose.yml   

#Docker Networks
networks:
  db-network:
  public:
    external: true
    name: traefik-network  

#Volumes
volumes:
    dbdata:
      driver: local    