version: '3.8'

name: "smart-repairs"

include:
  - docker/database/compose.yml
  - docker/knowledge/compose.yml

#Docker Networks
networks:
  db-network:
    driver: bridge
  knowledge-network:
    driver: bridge  

#Volumes
volumes:
    dbdata:
      driver: local    