version: '3.8'

services: 
  knwl-php:
    build:
      context: ./
      dockerfile: php/Dockerfile
      args:
        - php=${PHP}
    image: sm/knwl-php
    hostname: knwl-php
    environment:
      - DB_HOST=${DB_HOST}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    working_dir: /var/www
    volumes:
      - ${ROOT}src/knowledge:/var/www
    ports:
      - 9000:9000
    networks:
      - db-network    
      - knowledge-network  

  knwl-nginx:
    image: nginx:${NGINX}
    restart: unless-stopped
    hostname: knwl-nginx
    volumes:
      - ${ROOT}src/knowledge:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public
      - knowledge-network  
    depends_on:
      - knwl-php     
    labels:
      - "traefik.enable=true"    
      - "traefik.http.routers.knwl-nginx.rule=Host(`${API_SUBDOMAIN}.${HOST}`)"  
      - "traefik.http.routers.knwl-nginx.entrypoints=web"   

networks:
  knowledge-network:
    driver: bridge  