version: '3.8'

services: 

  knwl-php:
    build:
      context: ./
      dockerfile: php/Dockerfile
    image: sm/knwl-php
    hostname: knwl-php
    environment:
      - DB_HOST=${DB_HOST}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    working_dir: /var/www
    volumes:
      - ${ROOT}src/knowledge:/var/www
    ports:
      - 9000:9000
    networks:
      - db-network    
      - knowledge-network      

  knwl-nginx:
    image: nginx:alpine
    restart: unless-stopped
    hostname: knwl-nginx
    ports:
      - 8081:80
    volumes:
      - ${ROOT}src/knowledge:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - knowledge-network      
    depends_on:
      - knwl-php     