version: '3.8'

services: 
  traefik: #Traefix
    image: "traefik:${TRAEFIK}"
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock   
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - public

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.enable=true"    
      - "traefik.http.routers.whoami.rule=Host(`${HOST}`)" 
      - "traefik.http.routers.whoami.entrypoints=web"        
    networks:
      - public          